version: 0.0
os: linux
files:
  - source: hello.js
    destination: /var
hooks:
  BeforeInstall:
    - location: scripts/downloadnodejs.sh
      timeout: 300
      runas: root
      location: scripts/installnodejs.sh
      timeout: 300
      runas: root
