version: 0.0
os: linux
files:
  - source: codedeploy/amit.php
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
